# @package _global_
# primary config file for experiments

defaults:
  - _self_
  - env: all_1_high
  - policy: gnn_attn
  - baseline: rollout
  - meta: train
  - mk: mk3
  - hp_override: none
  - override hydra/job_logging: simple


hydra:
  # standard output path
  # change with command line argument: hydra.run.dir=XXX
  run:
    dir: outputs/${problem_id}_${graph_size}/${run_type}/mk${env_cfg.max_concurrent_vehicles}/pg_${baseline_cfg.baseline_type}/${policy_cfg.node_encoder_args.conv_type}/${now:%Y-%m-%d_%H-%M-%S}

  # overwrite root log level
  job_logging:
    root:
      level: ${log_lvl}

  #
  # help flag output. customize for application
  help:
    # App name, override to match the name your app is known by
    app_name: ${hydra.job.name}.py - train or evaluate specified models according to config.

    # Help header, customize to describe your app to your users
    header: |
      ${hydra.help.app_name}

    footer: |
      Use --hydra-help to view Hydra specific help

    template: |
      ${hydra.help.header}
      == Configuration groups ==
      Compose your configuration from those groups (group=option)

      $APP_CONFIG_GROUPS

      == Config ==
      Override anything in the config (foo.bar=value)

      $CONFIG

      ${hydra.help.footer}
